version: '3.8'

services:
  kai-backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - FIREBASE_TYPE=service_account
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_PRIVATE_KEY_ID=${FIREBASE_PRIVATE_KEY_ID}
      - FIREBASE_PRIVATE_KEY=${FIREBASE_PRIVATE_KEY}
      - FIREBASE_CLIENT_EMAIL=${FIREBASE_CLIENT_EMAIL}
      - FIREBASE_CLIENT_ID=${FIREBASE_CLIENT_ID}
      - FIREBASE_AUTH_URI=https://accounts.google.com/o/oauth2/auth
      - FIREBASE_TOKEN_URI=https://oauth2.googleapis.com/token
      - FIREBASE_AUTH_PROVIDER_CERT_URL=https://www.googleapis.com/oauth2/v1/certs
      - FIREBASE_CLIENT_CERT_URL=
      - FIREBASE_UNIVERSE_DOMAIN=
      - FIRESTORE_DB_NAME=${FIRESTORE_DB_NAME}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_ALGORITHM=HS256
    volumes:
      - .:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
