[tool.ruff]

line-length = 88

indent-width = 4

target-version = "py312"

exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
    "update_indexes.py",
    "configtest.py",
    "tools/*",
    "tests/*",
    "debug_dev/*",
    "alembic/versions/*"
]

[tool.ruff.lint]
# Basic rule sets
select = [
    "E",   # pycodestyle errors
    "F",   # pyflakes
    "I",   # isort
    "B",   # flake8-bugbear
    "C",   # flake8-comprehensions
    "T",   # flake8-debugger
    "D",   # pydocstyle
    "N",   # pep8-naming
    "UP",  # pyupgrade
    "ANN", # flake8-annotations
    "S",   # flake8-bandit (security)
    "A",   # flake8-builtins
    # "COM", # flake8-commas
    "RUF", # Ruff-specific rules
]

# Ignore specific rules
ignore = [
    "D100",  # Missing docstring in public module
    "D104",  # Missing docstring in public package
    "N802",  # Function name should be lowercase
    "D107",  # Missing docstring in __init__
    "B904",  # Use of assert in tests
    "ANN101", # Missing-type-self
    "ANN102", # Missing-type-cls
    "E501",  # Line too long (in docstrings)
    "ANN401", # Dynamically typed expressions
    "D413", # Missing blank line after last section ("Returns")
    "C901",
]

# File-specific rules
[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]  # Ignore unused imports in __init__.py
"tests/*" = ["S101"]      # Ignore assert statements in tests

[tool.ruff.format]

# Quote style
quote-style = "double"  # or "single"

# Indentation
indent-style = "space"


# Line endings
line-ending = "auto"  # or "lf", "crlf", "cr"

# Docstring format
docstring-code-format = true
docstring-code-line-length = 88

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false
